services:
  - type: web
    name: controle-dividas
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app.app:create_app()" --bind 0.0.0.0:$PORT
databases:
  - name: controle-dividas-db
    plan: free
